{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
env:
  - name: CLUSTER_NAME
    value: {{ .Values.clusterName }}
metadata:
  name: {{ include "wfs-demo.serviceAccountName" . }}
  labels:
    {{- include "wfs-demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
