apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-role-binding
roleRef:
  kind: Role
  name: access-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: arn:aws:iam::871606792318:user/devops@hllvc.com
