---
- name: Call Webhook
  tasks:
    - name: Call webhook
      uri:
        url: "{{ lookup('env', 'WEBHOOK_URL') }}"
        method: POST
        body_format: json
        body: "{{ webhook_data }}"
        headers:
          Content-Type: "application/json"

